force-app/main/default/objects/Additional_Org_Metrics__c/Additional_Org_Metrics__c.object-meta.xml
<CustomObject>
    <label>Additional Org Metric</label>
    <nameField>
        <displayFormat>AOM-{00000}</displayFormat>
        <label>Additional Org Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Org Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Org</fullName>
            </value>
            <value>
                <fullName>Validation Rules</fullName>
            </value>
            <value>
                <fullName>LimitsFieldsCustom</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>CodeUsageImprove</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>ExperienceUser</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Reports And Dashboards</fullName>
            </value>
            <value>
                <fullName>Increase User Adoption</fullName>
            </value>
            <value>
                <fullName>Improve Org Security</fullName>
            </value>
            <value>
                <fullName>Fields</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Objects</fullName>
            </value>
            <value>
                <fullName>Org Limit</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Feature_Type__c.field-meta.xml
<CustomField>
    <fullName>Feature_Type__c</fullName>
    <label>Feature Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned Page Layouts</fullName>
            </value>
            <value>
                <fullName>Unassigned Record Types</fullName>
            </value>
            <value>
                <fullName>Field Usage</fullName>
            </value>
            <value>
                <fullName>Inactive Workflow Rules</fullName>
            </value>
            <value>
                <fullName>Inactive Validation Rules</fullName>
            </value>
            <value>
                <fullName>Active Validation Rules</fullName>
            </value>
            <value>
                <fullName>Critical Permission Assignments</fullName>
            </value>
            <value>
                <fullName>Unused Reports</fullName>
            </value>
            <value>
                <fullName>PathLightning Sales Console</fullName>
            </value>
            <value>
                <fullName>Formula Fields with JavaScript Code</fullName>
            </value>
            <value>
                <fullName>Unused Dashboards</fullName>
            </value>
            <value>
                <fullName>Macros</fullName>
            </value>
            <value>
                <fullName>API Versions</fullName>
            </value>
            <value>
                <fullName>Fields on Page Layouts</fullName>
            </value>
            <value>
                <fullName>Multiple Apex Triggers per Object</fullName>
            </value>
            <value>
                <fullName>Unassigned Permission Sets</fullName>
            </value>
            <value>
                <fullName>Files Adoption</fullName>
            </value>
            <value>
                <fullName>Active Validation Rule Limits</fullName>
            </value>
            <value>
                <fullName>News and Twitter</fullName>
            </value>
            <value>
                <fullName>File Storage Limits</fullName>
            </value>
            <value>
                <fullName>Disable Debug Mode</fullName>
            </value>
            <value>
                <fullName>Unassigned Roles</fullName>
            </value>
            <value>
                <fullName>Details Tab on Record Pages</fullName>
            </value>
            <value>
                <fullName>S-Controls</fullName>
            </value>
            <value>
                <fullName>Active Workflow Rule Limits</fullName>
            </value>
            <value>
                <fullName>Inactive Chatter Users</fullName>
            </value>
            <value>
                <fullName>Omni-Channel</fullName>
            </value>
            <value>
                <fullName>Lightning Components on Record Lightning Pages</fullName>
            </value>
            <value>
                <fullName>Case Feed</fullName>
            </value>
            <value>
                <fullName>Migrating Workflow Rules to Flow Builder</fullName>
            </value>
            <value>
                <fullName>Active Workflow Rules</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Flow_Trigger_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Trigger_Type__c</fullName>
    <label>Flow Trigger Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Part_of_Managed_Package__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Managed_Package__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Part of Managed Package</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpeoAnalyzerWorflowMetricsBatch.cls
/**
 * @Version: 1.0
 * @Author: Frederik
 * @Copyright: 2021 Upeo Consulting
 * @Uses:
 *
 * -----------------------------------------------------------------------------------------------
 * Description: 
 *
 *
 * Created: 15/11/2021
 * Last Updated: 15/11/2021
 *
 * Unit tests:
 *
 * Change log:
 * -----------------------------------------------------------------------------------------------
*/
public class UpeoAnalyzerWorflowMetricsBatch implements Database.Batchable<Object>, Database.AllowsCallouts  {

    public list<Object> stringList = new List<Object>{'abc', 'def'};


    public Iterable <object> start(Database.BatchableContext BC) {

        String reqUrl = 'callout:UpeoOptimizer/services/data/v47.0/tooling/query/?q=' +
                'Select+Id,Name,TableEnumOrId+From+WorkflowRule';

        String responseBody = UpeoAnalyzerToolingRequest.request(reqUrl);

        UpeoAnalyzerWfrBasic wfrBasic = UpeoAnalyzerWfrBasic.parse(responseBody);

        List<Object> objList = wfrBasic.records;

        return objList;

    }

    public void execute(Database.BatchableContext BC, List<Object> scope) {

        List<Additional_Org_Metrics__c> addMetrics = new List<Additional_Org_Metrics__c>();

        for(Object o : scope){

            UpeoAnalyzerWfrBasic.cls_records detail = (UpeoAnalyzerWfrBasic.cls_records)o;
            Additional_Org_Metrics__c aom = new Additional_Org_Metrics__c();

            System.debug(detail.attributes.url);
            String detailUrl = (String) detail.attributes.url;
            String baseUrl = 'callout:UpeoOptimizer/';
            String wfrDetails = UpeoAnalyzerToolingRequest.request(baseUrl+detailUrl);
            WFRToolingResult wfrDetailResult = WFRToolingResult.parse(wfrDetails);

            aom.Component_Name__c = wfrDetailResult.Name;
            aom.Category__c = 'Workflow';
            if(wfrDetailResult.Metadata.active) {
                aom.Feature_Type__c = 'Active Workflow Rules';
            } else {
                aom.Feature_Type__c = 'Inactive Workflow Rules';
            }
            aom.Active__c = wfrDetailResult.Metadata.active;
            aom.Object__c = wfrDetailResult.TableEnumOrId;
            aom.External_Id__c = 'WFR' +wfrDetailResult.Id;
            aom.Flow_Trigger_Type__c = wfrDetailResult.Metadata.triggerType;
            if(wfrDetailResult.ManageableState.contains('installed')){
                aom.Part_of_Managed_Package__c = true;
            } else {aom.Part_of_Managed_Package__c = false;}

            addMetrics.add(aom);

        }

        upsert addMetrics External_Id__c;

    }




    public void finish(Database.BatchableContext BC){

    }

}