force-app/main/default/objects/Additional_Org_Metrics__c/Additional_Org_Metrics__c.object-meta.xml
<CustomObject>
    <label>Additional Org Metric</label>
    <nameField>
        <displayFormat>AOM-{00000}</displayFormat>
        <label>Additional Org Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Org Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Org</fullName>
            </value>
            <value>
                <fullName>Validation Rules</fullName>
            </value>
            <value>
                <fullName>LimitsFieldsCustom</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>CodeUsageImprove</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>ExperienceUser</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Reports And Dashboards</fullName>
            </value>
            <value>
                <fullName>Increase User Adoption</fullName>
            </value>
            <value>
                <fullName>Improve Org Security</fullName>
            </value>
            <value>
                <fullName>Fields</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Objects</fullName>
            </value>
            <value>
                <fullName>Org Limit</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Feature_Type__c.field-meta.xml
<CustomField>
    <fullName>Feature_Type__c</fullName>
    <label>Feature Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned Page Layouts</fullName>
            </value>
            <value>
                <fullName>Unassigned Record Types</fullName>
            </value>
            <value>
                <fullName>Field Usage</fullName>
            </value>
            <value>
                <fullName>Inactive Workflow Rules</fullName>
            </value>
            <value>
                <fullName>Inactive Validation Rules</fullName>
            </value>
            <value>
                <fullName>Active Validation Rules</fullName>
            </value>
            <value>
                <fullName>Critical Permission Assignments</fullName>
            </value>
            <value>
                <fullName>Unused Reports</fullName>
            </value>
            <value>
                <fullName>PathLightning Sales Console</fullName>
            </value>
            <value>
                <fullName>Formula Fields with JavaScript Code</fullName>
            </value>
            <value>
                <fullName>Unused Dashboards</fullName>
            </value>
            <value>
                <fullName>Macros</fullName>
            </value>
            <value>
                <fullName>API Versions</fullName>
            </value>
            <value>
                <fullName>Fields on Page Layouts</fullName>
            </value>
            <value>
                <fullName>Multiple Apex Triggers per Object</fullName>
            </value>
            <value>
                <fullName>Unassigned Permission Sets</fullName>
            </value>
            <value>
                <fullName>Files Adoption</fullName>
            </value>
            <value>
                <fullName>Active Validation Rule Limits</fullName>
            </value>
            <value>
                <fullName>News and Twitter</fullName>
            </value>
            <value>
                <fullName>File Storage Limits</fullName>
            </value>
            <value>
                <fullName>Disable Debug Mode</fullName>
            </value>
            <value>
                <fullName>Unassigned Roles</fullName>
            </value>
            <value>
                <fullName>Details Tab on Record Pages</fullName>
            </value>
            <value>
                <fullName>S-Controls</fullName>
            </value>
            <value>
                <fullName>Active Workflow Rule Limits</fullName>
            </value>
            <value>
                <fullName>Inactive Chatter Users</fullName>
            </value>
            <value>
                <fullName>Omni-Channel</fullName>
            </value>
            <value>
                <fullName>Lightning Components on Record Lightning Pages</fullName>
            </value>
            <value>
                <fullName>Case Feed</fullName>
            </value>
            <value>
                <fullName>Migrating Workflow Rules to Flow Builder</fullName>
            </value>
            <value>
                <fullName>Flow Runtimes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Flow_Execution_Times__c.field-meta.xml
<CustomField>
    <fullName>Flow_Execution_Times__c</fullName>
    <label>Flow Execution Times</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Flow_Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Flow_Last_Run__c</fullName>
    <label>Flow Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Flow_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Process_Type__c</fullName>
    <label>Flow Process Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Flow_Runtime_Duration__c.field-meta.xml
<CustomField>
    <fullName>Flow_Runtime_Duration__c</fullName>
    <label>Flow Runtime Duration</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Flow_Trigger_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Trigger_Type__c</fullName>
    <label>Flow Trigger Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpeoAnalyzerFlowMetricsController.cls
public class UpeoAnalyzerFlowMetricsController {
    
	@AuraEnabled
    public static List<sObject> fetchData() {
        //Query and return list of Contacts
        List<SObject> objRecords = [Select Name, Component_Name__c, Flow_Execution_Times__c, Flow_Last_Run__c, Flow_Process_Type__c, Flow_Runtime_Duration__c, Flow_Trigger_Type__c  from Additional_Org_Metrics__c where Category__c = 'Flow' and Feature_Type__c = 'Flow Runtimes'];
        return objRecords;
    }

	@AuraEnabled
    public static void flowMetrics(){
        system.debug('ran flowMetrics');
        UpeoAnalyzer.getFlowMetrics();
    }    

}