force-app/main/default/objects/Additional_Org_Metrics__c/Additional_Org_Metrics__c.object-meta.xml
<CustomObject>
    <label>Additional Org Metric</label>
    <nameField>
        <displayFormat>AOM-{00000}</displayFormat>
        <label>Additional Org Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Org Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Org</fullName>
            </value>
            <value>
                <fullName>Validation Rules</fullName>
            </value>
            <value>
                <fullName>LimitsFieldsCustom</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>CodeUsageImprove</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>ExperienceUser</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Reports And Dashboards</fullName>
            </value>
            <value>
                <fullName>Increase User Adoption</fullName>
            </value>
            <value>
                <fullName>Improve Org Security</fullName>
            </value>
            <value>
                <fullName>Fields</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Objects</fullName>
            </value>
            <value>
                <fullName>Org Limit</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Feature_Type__c.field-meta.xml
<CustomField>
    <fullName>Feature_Type__c</fullName>
    <label>Feature Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned Page Layouts</fullName>
            </value>
            <value>
                <fullName>Unassigned Record Types</fullName>
            </value>
            <value>
                <fullName>Field Usage</fullName>
            </value>
            <value>
                <fullName>Inactive Workflow Rules</fullName>
            </value>
            <value>
                <fullName>Inactive Validation Rules</fullName>
            </value>
            <value>
                <fullName>Active Validation Rules</fullName>
            </value>
            <value>
                <fullName>Critical Permission Assignments</fullName>
            </value>
            <value>
                <fullName>Unused Reports</fullName>
            </value>
            <value>
                <fullName>PathLightning Sales Console</fullName>
            </value>
            <value>
                <fullName>Formula Fields with JavaScript Code</fullName>
            </value>
            <value>
                <fullName>Unused Dashboards</fullName>
            </value>
            <value>
                <fullName>Macros</fullName>
            </value>
            <value>
                <fullName>API Versions</fullName>
            </value>
            <value>
                <fullName>Fields on Page Layouts</fullName>
            </value>
            <value>
                <fullName>Multiple Apex Triggers per Object</fullName>
            </value>
            <value>
                <fullName>Unassigned Permission Sets</fullName>
            </value>
            <value>
                <fullName>Files Adoption</fullName>
            </value>
            <value>
                <fullName>Active Validation Rule Limits</fullName>
            </value>
            <value>
                <fullName>News and Twitter</fullName>
            </value>
            <value>
                <fullName>File Storage Limits</fullName>
            </value>
            <value>
                <fullName>Disable Debug Mode</fullName>
            </value>
            <value>
                <fullName>Unassigned Roles</fullName>
            </value>
            <value>
                <fullName>Details Tab on Record Pages</fullName>
            </value>
            <value>
                <fullName>S-Controls</fullName>
            </value>
            <value>
                <fullName>Active Workflow Rule Limits</fullName>
            </value>
            <value>
                <fullName>Inactive Chatter Users</fullName>
            </value>
            <value>
                <fullName>Omni-Channel</fullName>
            </value>
            <value>
                <fullName>Lightning Components on Record Lightning Pages</fullName>
            </value>
            <value>
                <fullName>Case Feed</fullName>
            </value>
            <value>
                <fullName>Migrating Workflow Rules to Flow Builder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Records_where_not_Used__c.field-meta.xml
<CustomField>
    <fullName>Records_where_not_Used__c</fullName>
    <label>Records where not Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Additional_Org_Metrics__c/fields/Records_where_Used__c.field-meta.xml
<CustomField>
    <fullName>Records_where_Used__c</fullName>
    <label>Records where Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SelectedBatchFieldUsage.cls
/**
 * Created by fpardon on 10/11/2021.
 */

public class SelectedBatchFieldUsage implements Database.Batchable<sObject> {

    private final String Query;
    private List<String> FieldStringList;
    private String ObjType;

    public SelectedBatchFieldUsage(String qryString, List<String> fieldList, String objType){
        this.Query = qryString;
        this.FieldStringList = fieldList;
        this.ObjType = objType;

        system.debug('fieldMap size = ' +fieldList.size());
        system.debug('objectType = ' +objType);
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator(query);

    }

    public void execute(Database.BatchableContext BC, List<sObject> fieldList) {


        List<Additional_Org_Metrics__c> lstOrgMetrics = new List<Additional_Org_Metrics__c>();

        system.debug('Object Type = '+ObjType);
        System.debug('Field List Size = ' + FieldList.size());
        SObjectType type = Schema.getGlobalDescribe().get(objType);
        Map<String, Schema.SObjectField> fieldMap = type.getDescribe().fields.getMap();

        for(String field :FieldStringList) {

            Additional_Org_Metrics__c aom = new Additional_Org_Metrics__c();
            aom.Category__c = 'Fields';
            aom.Feature_Type__c = 'Field Usage';
            aom.Object__c = objType;
            aom.External_Id__c = objType + '-' + field;
            aom.Custom__c = fieldMap.get(field).getDescribe().isCustom();
            aom.Component_Name__c = fieldMap.get(field).getDescribe().getName();
            aom.Records_where_Used__c = 0;
            aom.Records_where_not_Used__c = 0;
            aom.Total_Records__c = 0;

            for (SObject rec : fieldList) {
                if (rec.get(field) == null) {
                    aom.Records_where_not_Used__c++;
                    aom.Total_Records__c++;
                }
                if (rec.get(field) != null) {
                    aom.Records_where_Used__c++;
                    aom.Total_Records__c++;
                }
            }

            lstOrgMetrics.add(aom);

        }
        upsert lstOrgMetrics External_Id__c;

        system.debug('Number of metrics to be added ' +lstOrgMetrics.size());

    }

    public void finish(Database.BatchableContext BC){

    }

}